<a href="https://colab.research.google.com/github/nirudi98/IrisClusteringNN/blob/master/NeuralNetworkIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Neural Network implementation with google colab
#Iris.csv is added to files and loaded
#This code is used to cluster Iris data


#importing necessary packages

import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns


# Assign the csv data to a DataFrame
iris_data = pd.read_csv("/content/sample_data/Iris (1).csv")


# defining class labels (3 classes)
labels = ["Iris-sentosa","Iris-versicolor","Iris-virginica"]


# Print the first 10 instances
print("first 10 instances of Iris : \n", iris_data.head(10).style)

# skipping a blank row
print("\n")


# prnit Information of the dataset
print("dataset information : \n", iris_data.info())

# skipping a blank row
print("\n")


# Dimensions of the dataset
print("dimensions of the dataset : ", iris_data.shape)

# skipping a blank row
print("\n")


# Encoding labels using hot encoding approch - this appraoch makes it easy to read the output data
# using a function and returning the encoded target
def target_hotencoding(target):
    encoded_target = pd.DataFrame()
    for label in target.unique():
        encoded_target[label] = np.where(target == label, 1, 0)
    return encoded_target



#input data and the target
X=iris_data.iloc[0:,1:5]
y=iris_data.iloc[0:,5] 


# normalize the train data attributes
normalized_X = preprocessing.normalize(X)
print("normalized X : \n", normalized_X)


#hot encode of the output - sending the output labels into hthe encoding function
target = target_hotencoding(y)
#print(y)



#---------------------------------------------------------------------------------------#
                        
                             #implementing neural network


print("----------------------------------------------------------------- \n")
print("Neural Network Implementation \n ")


#generating weights randomly - since 3 hidden layer neurons and 4 input nodes (4,3) matrix
np.random.seed(5)
W = np.random.rand(4,3)


#generating bias randomly - since 3 hidden layer neurons (3,1) matrix
bias = np.random.rand(3,1)


#learning rate - learning rate value should be between 0 - 1 
lr = 0.05

# normalize the randomly generated weights
weights = preprocessing.normalize(W)


#printing the random weights
#print("randomly generated weights \n",weights)
#print("randomly generated bias \n",bias)
#print("SHAPE OF weights :", normalized_weights.shape)



#weighted sum of hidden layer node or output layer node
#activation function to get the output (sigmoid)

# activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

# finding the deriviative of the value returning from sigmoid function
def sigmoid_der(x):
    return x*(1-x)


# feed forward and backpropagration part 
# R=500 loop 

for iteration in range(500):
    inputs = normalized_X

   # feedforward step 1 - calculating the weighted sum 
    XW = (np.dot(normalized_X, weights)+ (bias.T))
    # + (bias.T)
    

   # feedforward step 2 - passing the weighted output to sigmiod function and assigning the returned value to z
    z = sigmoid(XW)

   # converting returned output to a matrix of zero and then representing the maximum value using 1   
    output = np.zeros_like(z)
    output[np.arange(len(z)), z.argmax(1)] = 1


   # Casting float values to int
    output = output.astype(int)
    
   #print(output)

   # calculating the mean squared error and printing MSE for each iteration
    MSE = np.mean(np.square(output - target))
    print("iteration ", iteration, "MSE : \n", )
    print(MSE)
    
   # skipping line
    print("\n")
   # output is my predicted value / target is the observed or given value
   # backpropagation step 1 (differentiating MSE using chain rule - constants are ignored)
    error_of_output = (output - target)


   # applying chain rule of differentiation
   # dcost :derivation of cost function with respect to weight
   # dcost_dpred : derivation of cost function with respect to sigmoid function
    

   # backpropagation step 2
    dcost_dpred = error_of_output

    dpred_dz = sigmoid_der(z)

    z_delta = dcost_dpred * dpred_dz

   # inputs_weights = normalized_X
   # directly multiplying the transpose of input matrix with corresponding z_delta
    inputs = normalized_X.T
    
   # multiplying by lr to increase the speed of convergence
    weights = weights - (lr * np.dot(inputs, z_delta))
    

   # normalizing the updated weights
    weights = preprocessing.normalize(weights)

   
   # updating the bias
   #dl_wrt_b1 = np.sum(z_delta, axis=0)
   #bias = bias - (lr*dl_wrt_b1)


   # end of the loop

print("\n")

#---------------------------------------------------------------------------------------#
                        
                             #displaying the output of the CNN - clusters


print("----------------------------------------------------------------- \n")
print("Final Prediction of Neural Network \n ")


# calculating the final prediction using final updated weights and inputs and sending to sigmoid
final_prediction  = sigmoid(np.dot(normalized_X, weights))

# converting the final output to zeros matrix and replacing the maximum amount with 1
prediction = np.zeros_like(final_prediction)
prediction[np.arange(len(final_prediction)), final_prediction.argmax(1)] = 1
prediction = prediction.astype(int)

# adding the final prediction to a dataframe - columns are labels
prediction = pd.DataFrame(prediction, columns=labels)

# printing clustered value using a for looping, looping through the dataframe
print("Clustered values : ")

for cluster in prediction.columns: 
   print("\t",cluster , ":", prediction[cluster].sum())


print("\n")

# plotting the final prediction in a graph 
# plt.plot(prediction)
# plt.show()
print("\n")

#---------------------------------------------------------------------------------------#
                        
                             #purity clustering section of the code
print("----------------------------------------------------------------- \n")
print("Purity Clustering of the Final Prediction of Neural Network \n ")

# importing necessary packages

import numpy as np
from sklearn import metrics

# function to compute the purity score
def purity_score(y_true, y_pred):

    # compute contingency matrix (also called confusion matrix)
    contingency_matrix = metrics.cluster.contingency_matrix(y_true, y_pred)

    print(contingency_matrix)

    #finding the max of every row in the matrix
    max_contigencyMatrix = np.amax(contingency_matrix,axis=0)

    #sum of all max values
    sum_max_contigencyMatrix = np.sum(max_contigencyMatrix)

    #total number of data points in the matrix
    tot_dataPoints = np.sum(contingency_matrix) 

    # return purity 
    return sum_max_contigencyMatrix/tot_dataPoints


# calling the purity score function by passing the target and prediction values - purity_score function
# printing purity score
print("purity score of CNN Iris clustering : " ,purity_score(target,prediction))

first 10 instances of Iris : 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
dataset information : 
 None


dimensions of the dataset :  (150, 6)


normalized X : 
 [[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80003025 0.53915082 0.26087943 0.03478392]
 [0.790965   0.5694948  0.2214702  0.0316386 ]
 [0.78417499 0.5663486  0.2468699  0.05808704]
 [0.78010936 0.57660257 0.23742459 0.0508767 ]
 [0.80218492 0.54548574 0.2406554

In [ ]:
#removing bias
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns


# Assign the csv data to a DataFrame
iris_data = pd.read_csv("/content/sample_data/Iris (1).csv")

#class labels
labels = ["Iris-sentosa","Iris-versicolor","Iris-virginica"]

# Print the first 10 instances
iris_data.head(10).style

# Information on the dataset
iris_data.info()

# Encoding labels using hot encoding approch
def target_hotencoding(target):
    encoded_target = pd.DataFrame()
    for label in target.unique():
        encoded_target[label] = np.where(target == label, 1, 0)
    return encoded_target




# Total Instances on each iris plant class
print(iris_data["Species"].value_counts())

# Dimensions of the dataset
iris_data.shape

#input data and the target
X=iris_data.iloc[0:,1:5]
y=iris_data.iloc[0:,5] 




# normalize the train data attributes
normalized_X = preprocessing.normalize(X)
#normalized_X

#hot encode of the output
target = target_hotencoding(y)
#print(y)

#---------------------------------------------------------------------------------------#
                        
                             #implementing neural network

#generating weights randomly
np.random.seed(5)
W = np.random.rand(4,3)

#generating bias randomly
bias = np.random.rand(3,1)

#learning rate
lr = 0.05

print("\n")

#printing the random weights
#print("randomly generated weights \n",weights)

print("\n")

# normalize the randomly generated weights
weights = preprocessing.normalize(W)

#print("randomly generated bias \n",bias)
#print("SHAPE OF weights :", normalized_weights.shape)


#weighted sum of hidden layer node or output layer node
#activation function to get the output (sigmoid)

#activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

#finding the deriviative of the value returning from sigmoid function
def sigmoid_der(x):
    return x*(1-x)

m = target.shape[1]

#feed forward and backpropagration
for iteration in range(500):
    inputs = normalized_X


   # feedforward step 1- calculating the weighted sum
    #XW = (np.dot(normalized_X, weights) + (bias.T))
    XW = (np.dot(normalized_X, weights))

   #feedforward step 2 - passing the weighted output to sigmiod 
    z = sigmoid(XW)
    output = np.zeros_like(z)
    output[np.arange(len(z)), z.argmax(1)] = 1

    # Casting float values to int
    output = output.astype(int)
    
    #print(output)


   #calculating the mean squared error
    MSE = np.mean(np.square(target-output))
    print(iteration, " : ")
    print("ERROR = \n",MSE)
    
    # backpropagation step 1
    error_of_output = output - (target)

    #applying chain rule of differentiation
    #dcost :derivation of cost function with respect to weight
    #dcost_dpred : derivation of cost function with respect to sigmoid function
    

    # backpropagation step 2
    dcost_dpred = error_of_output

    #n12 = np.squeeze(np.asarray(z))
    dpred_dz = sigmoid_der(z)

    z_delta = dcost_dpred * dpred_dz

    #inputs_weights = normalized_X
    #directly multiplying the transpose of input matrix with corresponding z_delta
    inputs = normalized_X.T
    
    #multiplying by lr to increase the speed of convergence
    weights = weights - (lr * np.dot(inputs, z_delta))
    
    db2 = (1 / m) * np.sum(error_of_output, axis = 1) 
    print("db2 :",db2)

    bias = bias - (lr*db2)
    print(bias)
    #for num in z_delta:
      #bias = bias - (lr * num)

    weights = preprocessing.normalize(weights)

    #bias = bias - (lr * np.dot(bias, 1))
    #print(bias)




#plt.plot(error_of_output)
#plt.show()

final_prediction  = sigmoid(np.dot(normalized_X, weights))

prediction = np.zeros_like(final_prediction)

prediction[np.arange(len(final_prediction)), final_prediction.argmax(1)] = 1
prediction = prediction.astype(int)


prediction = pd.DataFrame(prediction, columns=labels)
print(f"Clustered values :")
for cluster in prediction.columns:  print(f"\t{cluster} : {prediction[cluster].sum()}")

 #-----------------------------------------------------------------------------------------------#
#purity clustering
import numpy as np
from sklearn import metrics
from scipy.optimize import linear_sum_assignment

def cluster_accuracy(y_true, y_pred):
    # compute contingency matrix (also called confusion matrix)
    contingency_matrix = metrics.cluster.contingency_matrix(y_true, y_pred)
    print(contingency_matrix)

    # Find optimal one-to-one mapping between cluster labels and true labels
    row_ind, col_ind = linear_sum_assignment(-contingency_matrix)

    # Return cluster accuracy
    return contingency_matrix[row_ind, col_ind].sum() / np.sum(contingency_matrix)


print(cluster_accuracy(target,prediction))

 
 



